TEAM_MAP = {
    '#1 Victory Royale': '1VR',
    '+22 ': '+22',
    '+W party': '+WP',
    '-sheesh-': '-she',
    '0 Training': '',
    '100 Blifted': '100B',
    '100 Thieves': '100T',
    '100emoji': 'DIG',
    '123TAP': '123T',
    '1280x960': '4x3',
    '1337': '1337',
    '1337va': '1337',
    '153': '153',
    '1620 Kings': 'K16',
    '19esports': '19',
    '1HP': '1HP',
    '1Tap Tavern': '1TT',
    '1stCav eSport Club': '1stC',
    '200 Policemen': '200P',
    '24Haven': '24/H',
    '2G4L': '2G4L',
    '2red': '2red',
    '30% BF': '30BF',
    '303 Esports': '303',
    '303 Esports Orange': '',
    '335 Cầu Giấy': 'Kantic',
    '368': '368',
    '3BL Esports': '3BL',
    '4 lixo + Nikinho': '',
    '47 Gaming': '47',
    '4Fun': '4Fun',
    '4Q': '4Q',
    '4fan': '4fan',
    '5 Randoms': '',
    '5 Yung Drillas': '',
    '5Dogs': '5Dog',
    '5MOKES': '5M',
    '5NOOBS': '5N',
    '5Ravens': '5RS',
    '5gg': '5gg',
    '5up': '5up',
    '5ynerG': '5yne',
    '6045Pirates': 'PIR',
    '666': '666',
    '95x eSports': '95x',
    '99Percent.': '99PT',
    '99cents': '99C',
    '9XL': '123',
    '9z Team': '9z',
    'A SEITA': '',
    'A$AP': 'A$AP',
    'A.S.M.R.': 'ASMR',
    'ABB ASKI E-Spor WHITE': 'ABB',
    'ABC Boiz': 'DIG',
    'AERIS': 'AERI',
    'AFTERMIND': 'AM',
    'AG': 'AG',
    'AG.Nefarious': 'AG.N',
    'AGAiN': 'AGAi',
    'AGG': 'AGG',
    'AKATSUKI': '',
    'AKIHABARA ENCOUNT': 'AE',
    'ALCYONE': 'ALCY',
    'ALFA Esport': 'ALFA',
    'ALL GAS NO BRAKES': 'Ghost',
    'ANARCHY': 'AR',
    'ANBU Elite Gaming': 'ANBU',
    'ANEW Esports': 'ANEW',
    'ANKA E-Sports': 'ANKA',
    'ANYWAY': 'ANYW',
    'APEX PEOPLE': 'APEX',
    'ARBIES': 'ARBI',
    'ARDENT': 'ARDE',
    'AREA': 'AREA',
    'ARES Gaming': 'ARES',
    'ASI': 'ASI',
    'ATK Mode': 'ATK',
    'ATRAVS': 'ATR',
    'ATROPELADOS': 'ATRO',
    'AU POINT': '',
    'AUTOCRACY': 'AUTO',
    'AVALON Gaming': 'AG',
    'AVENUE Esports': 'AVENUE',
    'AVEZ Esport': 'AVEZ',
    'AXIBYTE ESPORTS': 'AXI',
    'AYB Esports': 'AYB',
    'Able Esports': 'AE',
    'AboveCloud': 'ABC',
    'Absolute JUPITER': 'JUP',
    'Absolute Legends': 'aL',
    'Absolute Legends Blue': '',
    'Acend': 'ACE',
    'Ackerman Team': 'ACE',
    'Acolarse': 'EZG',
    'Action PH': 'APH',
    'Activat3D Esports': 'A3D',
    'Actually Homeless': 'Actu',
    'Adept esport': 'AE',
    'Admirals': 'Admi',
    'Aerstream Esports': 'Aers',
    'Affinity Esports': 'AFN',
    'Against All Odds': 'AAO',
    'Agentes Livres': 'Agen',
    'Aggie Gaming at UC': 'Aggi',
    'Ah yeah gaming': '',
    'Ahjin': 'Ahji',
    'Ahlman Esports': 'AE',
    'Aim from Kitchen': 'Aim',
    'Aim.Attack': 'AMT',
    'Aion Esports': 'Aion',
    'Akademus Esport': 'AKA',
    'Akatsuki': 'Akat',
    'Akave Esports': 'AKV',
    'Akella': 'Akel',
    'Akrew': 'Akre',
    'Akuma Esports': 'Akum',
    'All Around Savants': 'AAS',
    'All Born to Clutch': 'ABC',
    'All Day Long': 'ADL',
    'All Gamers': 'AG',
    'All Victory Esports': 'AV',
    'Alliance': '[A]',
    'Allware': 'ALLW',
    'AlmondLatte': 'AL',
    'Alpha Esports Pro': 'AE',
    'Alpha Six Gaming': 'ASG',
    'Alter Ego': 'AE',
    'Alter Ego Celestè': 'AECL',
    'Altered Edge': 'AE',
    'Alterfox Esports': 'Alte',
    'Amarok Esports ': 'ABX',
    'Amateur Team': 'AT',
    'Ambitious': 'A',
    'Ambush': 'MYS',
    'Anata': 'Anat',
    'Anatolia Esports': 'AES',
    'Anavrin Esports': 'SR',
    'Andbox': 'ABX',
    'Angel Wings': 'AW',
    'Angels': 'Ange',
    'Angry Titans': 'AT',
    'Anime Aimers': 'PK',
    'Anime Club(Want It Gaming)': 'RNG',
    'Anime Super Soldiers': 'Anim',
    'Anonymo Esports': 'Anon',
    'Anti Eco Eco Club': 'AEEC',
    'Anubis Gaming': 'ANB',
    'Anuncie Aqui': 'ANA',
    'Anuncie Aqui(Anuncie Aqui)': 'ANA',
    'AoeXe': 'AoeX',
    'Apex': 'Apex',
    'Apexis': 'Apex',
    'Aqua': 'Aqua',
    'Aqualix': 'AQLX',
    'Aquatik': 'Aqua',
    'Aracne Esports': 'TS',
    'Arbalest': 'ABL',
    'Arcana': 'Arca',
    'Arcane(Roosters)': 'ROO',
    'ArchiGoKill': 'AG',
    'Archons': 'ARCH',
    'Arctic Gaming': 'AG',
    'Arctic Gaming Mexico': 'AGM',
    'Aricat Esport': 'ARC',
    'Aricat.Aresta': 'ARIC',
    'Ark5': 'Ark5',
    'ArkAngel': 'AA',
    'Armory Gaming': 'AG',
    'Art of Throwing': 'AOT',
    'Aspire': 'Aspi',
    'Aspyre': 'ASP',
    'Asteria Gaming': 'AG',
    'Atheris Esports': 'Athe',
    'Athletico Zombies': 'ATHZ',
    'Atletica Pro Gaming 9': 'A9',
    'AtmosFear': 'AF',
    'Attack All Around': 'AAA',
    'Attacking Soul Esports': 'ASE',
    'Australs': 'AUS',
    'Austrian Force(alltheRAGE)': 'atR',
    'Avant': 'AV',
    'Average Joes': 'AvgJ',
    'Avocados Team': 'Avoc',
    'Awake Esports': 'AE',
    'Axolotl': 'Axol',
    'Axsor': 'AX',
    'B Beasts': 'BB',
    'B4 Angels': 'B4A',
    'B4 eSports': 'B4',
    'B7 Warriors': 'B7',
    'BADARANTS': 'BADA',
    'BADARANTS(VIMDOLOL)': 'VIMD',
    'BAG8': 'PP',
    'BAKEMON': 'BMN',
    'BALANCED?': 'BALA',
    'BANDYCI': 'BAND',
    'BAR100LONA': 'BAR1',
    'BBL Esports': 'BBL',
    'BBL Queens': 'BBL',
    'BDV': 'BDV',
    'BE FUN SWORD': '',
    'BE INFAMOUS': 'BI',
    'BEAST': 'BST',
    'BETA': 'BETA',
    'BIG': 'BIG',
    'BIG BOY\'S CLUB': 'BIG',
    'BIG SCYTHE': 'BIGG',
    'BK ROG Esports': '',
    'BLAHAJ': 'BLAH',
    'BLOKES': 'BLOK',
    'BLUEJAYS Frates': 'AKA',
    'BOOM Esports': 'BME',
    'BRACIA': 'BRAC',
    'BRAVOS GAMING': 'BRAV',
    'BTR ': 'BTR',
    'BULLS Esports': 'BBL',
    'BWG': 'BWG',
    'BYE': 'S8v',
    'Bad Boy Crew': 'Bad',
    'Badmental Badgame': 'BB',
    'Bait Academy': 'BA',
    'Balanced Esports': 'Bala',
    'Ballista': 'BST',
    'BananaBoys': 'Bana',
    'Banbind': '',
    'Bandits': 'BNDT',
    'Banditz': 'AT',
    'Bantz': 'Bant',
    'Barely Acceptable': 'Bare',
    'Barrados Do Divine': 'Barr',
    'Bay Area Vandals': 'BAV',
    'BearClaw Gaming': 'BCG',
    'Bedel Ödeyenler': 'Bedel',
    'BeeNinjas': 'BeeN',
    'Begrip Gaming': 'Begrip',
    'Bencheados': 'Benc',
    'Bencheados Academy': 'Benc',
    'Benchwarmers': 'Benc',
    'Besiktas Esports': 'BJK',
    'Besiktas Esports Female': 'Besi',
    'Bestial': '',
    'Beta Irons': 'BFe',
    'Betrayed\'s Fantasy Team': 'Betr',
    'Bewds Retirement Home': 'BRH',
    'Beyond Infinity': 'FNG',
    'Bifrost': 'Bifr',
    'Big Backwoods': 'Big',
    'Big Baller Brand': 'Big',
    'Big Bang': 'BB',
    'Big Frames': 'BF',
    'Big Gains': 'Big',
    'BigBrainDOGS': 'BigB',
    'Bigetron Astro': 'BTR',
    'Bingueiros': 'VK',
    'Bizarre Gaming': 'BZR',
    'Bjor\'s Kittens': 'Bjor',
    'Black Bears': 'Blac',
    'Black Dragons': 'BD',
    'BlackBelts': '',
    'BlackBird Ignis': 'BBI',
    'Bleed eSports': 'BLEED',
    'Bleiz': 'AAO',
    'Blitz': 'Blit',
    'Bloodsport': 'Bloo',
    'Bloom': 'BLOOM',
    'Bnat Char9i': 'Bnat',
    'Boberts-Bugs-B-Gone': 'Bobe',
    'Boca Boston': 'BB',
    'Bonde da Loli Careca': 'Bond',
    'Bongos': 'Bong',
    'Bonk Babes': 'Bonk',
    'Bonk(bonk)': 'Demi',
    'Bonsoir': 'Bons',
    'Booster Seat Gaming': 'Boos',
    'Border Monsters': 'BOM',
    'Borderline': 'NSNP',
    'Born to win': 'BTW',
    'Boss Gold': 'BOG',
    'Botafogo eSports': 'VK',
    'Bottom Fraggers': 'BF',
    'Bottom as always': 'Bott',
    'Bounty Esports': 'Boun',
    'Brain And Friends': 'Brai',
    'Brave': 'BRV',
    'Breakout': 'Brea',
    'Bren Esports': 'BRN',
    'Brimstone Gaming': 'Brim',
    'Brolympics eSports': 'Brol',
    'Broskis': 'Bros',
    'Brotherhood of the Five': 'B5',
    'Budapest5(Arbalest)': 'ABL',
    'Builders': 'BLD',
    'Built By Gamers': 'BBG',
    'Built By Gamers Academy': 'BBG.A',
    'Bulldozer Gaming': 'BDG',
    'Bully Hunters': 'Bull',
    'Bunker Esports': 'Bunk',
    'Bunkergg': 'Bunk',
    'Burton n Friends': 'Burt',
    'Buscando Org': 'Busc',
    'Békéscsabai E-sport Egyesület': 'BEE',
    'CANAVARLAR': 'CNVR',
    'CBT Gaming': 'CBT',
    'CC Angels': '',
    'CE Calling': 'CEC',
    'CERBERUS Esports': 'CES',
    'CGN Esports': 'CGN',
    'CH1LL': 'CH1L',
    'CISFAITH': 'CISF',
    'CITRON CHIEN': 'CC',
    'CLB': 'CLB',
    'CLG Red': 'CLG',
    'CLMRT': 'CLMR',
    'CNCI BLUE BEES': 'BB',
    'CNG Esports': 'CNG',
    'COFFEE': 'COFF',
    'COMETA TEAM': 'COM',
    'CONCENTRA SOVA': 'IMP',
    'CONSTIPEEK(RainbowMind)': 'RbM',
    'COUSINS': 'COUS',
    'CR4ZY': 'CR4Z',
    'CYCLOPS athlete gaming': 'CAG',
    'Caffeine Fiends': 'MR',
    'Cage Triggered': 'Cage',
    'Cairo City G\'zzz': 'CCG',
    'Cakebois': 'Cake',
    'Carnos Arks': 'Carn',
    'Carpe Noctem': 'CN',
    'Carpet Cleaners': 'Carp',
    'Casaless': 'Casa',
    'Case Esports': 'Case',
    'Castaways': 'Cast',
    'Cataclysm Team': 'CT',
    'Catalyst Esports': '1stC',
    'Catolica Esports': 'Cato',
    'Caught in 4k': '100T',
    'Cave Canem': 'CAVE',
    'Celeste': 'CLST',
    'Celestial Violet': 'C9',
    'Chakalaka': 'AKA',
    'Chariot': 'Char',
    'Charlotte Phoenix': 'CLT',
    'ChatBanned': 'Chat',
    'Chichaland': '',
    'Chick Fil Ayy': 'BM',
    'ChillinWithFriends': 'Chil',
    'Chilling in Space': 'Chil',
    'Chimaera': 'Chim',
    'China Nguyen': 'CN',
    'Chivas Esports': 'CHI',
    'Chobome Esports(OOKERS)': 'COL',
    'Christians Rottweilers': 'Chri',
    'Cicka123': 'DA',
    'Circe': 'Circ',
    'Clan123': 'C123',
    'Clarity Esports': 'Arrow',
    'Cloud9': 'C9',
    'Cloud9 Academy': 'C9A',
    'Cloud9 Korea': '',
    'Cloud9 White ': 'C9W',
    'Clover': '',
    'Clutch Jeans': 'CJ',
    'CoT': 'CoT',
    'Code7': 'C7',
    'Collateral eSports': 'CES',
    'Complexity': 'COL',
    'Complexity GX3': 'GX3',
    'Connect Gaming': 'COG',
    'Constant rise': 'Cons',
    'Control': 'CTRL',
    'Control(Air Raiders)': 'AR',
    'Cool Guys': 'cG',
    'Coquinha 2L': 'Coqu',
    'CoreNine Esports': 'CNE',
    'Cosmic Divide': 'CD',
    'Crab Walk Killers': 'CWK',
    'Cracked': 'Crac',
    'Cracked and Dialed': 'CAD',
    'Crash Landin on You': 'CLOY',
    'Crazy Hamster': '',
    'Crazy Raccoon': 'CR',
    'Cream Real Betis': 'BTS',
    'Creme brulee': 'GUILD',
    'Crest Gaming': 'CG',
    'Crew Esports': 'Crew',
    'Crimas Disciples': 'Crim',
    'Croccers(Kanga Esports)': 'KNG',
    'CrowСrowd': 'СС',
    'Cruzados Esports': 'Cruz',
    'Cruzeiro Esports': 'CRZ',
    'Crypto Esports': 'CE',
    'Cube Esports': 'Cube',
    'Cursed Team': 'Curs',
    'Cyber Skull Esports': 'CSE',
    'Cynical': 'CNL',
    'D2E Gold': 'D2E',
    'DAMWON Gaming': 'DWG',
    'DAT': 'Aspi',
    'DAVR': 'GLB',
    'DELIRAWOW': 'DLWZK',
    'DETONA Gaming': 'DG',
    'DEVOTEES': 'BBL',
    'DFR': 'DFR',
    'DFT Revitalize': 'DFT',
    'DIRTY': 'DIRT',
    'DIVAN': 'VIT',
    'DIVIZE': 'IVI',
    'DKS Esports': 'DKS',
    'DNA PEEK': 'BST',
    'DNADIFF': 'DNAD',
    'DOMINUS': 'DOM',
    'DOODAY': 'DOOD',
    'DPE': 'DPE',
    'DR Esports': 'DR',
    'DREAMCHASERS': 'DC',
    'DREAMLAND': 'DL',
    'DRMZ Esports': 'SQ',
    'DRX Vision Strikers': 'DRX',
    'DaBaby Clan': 'DaBa',
    'DaHoonkaBhanKoloos(Kooky Koalas )': 'KK',
    'Dallas Vendetta': 'DV',
    'Damaru Gaming': 'DG',
    'Dambis': 'DMB',
    'Damianos Esport': 'Dami',
    'Damn I Love Fwogs': 'DILF',
    'Dark Matter Purple': 'T1',
    'Dark Passage': 'DP',
    'Dark Tempest': '3BL',
    'Dark Tigers': 'DTG',
    'DarkZero Esports ': 'DZ',
    'Darkness': 'Dark',
    'Dawn of Stars': 'DOS',
    'Daycare': 'Dayc',
    'Daytrade Gaming': 'Dayt',
    'DeToNator': 'DTN',
    'Dead Rabbits': 'Dead',
    'Dead Silence': 'Dead',
    'Deadlife': 'Dead',
    'Decent Esports': 'Dece',
    'Decisive': 'DCSV',
    'DeftFox': 'DFX',
    'Deja Vu': 'Deja',
    'Dem Boys Cold': 'DBC',
    'Demise': 'Demi',
    'Demon': 'Demo',
    'Demon Time': 'DT',
    'Depth': 'Dept',
    'Derrek and Friends(ex-Phoenix1)': 'ROO',
    'Designated': 'Desi',
    'Destined': 'Dest',
    'DetonatioN Gaming White': 'DGW',
    'DevilDucks': 'Devi',
    'Dewa United Esports V3': 'DEWA',
    'Dewa VVV': 'Dewa',
    'DfuseTeam': 'DFUSE',
    'Dia De Los Muertos': 'DDLM',
    'DiaXmix': 'GIA',
    'Digital Athletics': 'DA',
    'Digital Ninjas': 'DNJ',
    'Dignitas': 'DIG',
    'Dignitas ': 'DIG',
    'DimmaDome$': 'DD$',
    'DingFeng Gaming': 'Ding',
    'Dire Wolves': 'DW',
    'Disciples ': 'Disc',
    'Divine': 'DV',
    'Divine Vendetta': 'DV',
    'Divinity': 'Divi',
    'DivisionX Gaming': 'DXG',
    'Dog Team Needs Club Org': 'DTNC',
    'Don\'t Even Ask': 'DEA',
    'Dontcare': 'Dont',
    'Double Vision': 'VRT',
    'Down Two Earth': 'D2E',
    'DownBad': 'Down',
    'DrAgOnZz': 'DrAg',
    'Dream Team': 'Drea',
    'DreamFyre': 'DF',
    'DreamSeller': 'DS',
    'Dreamwalker': 'DRM',
    'Drop Shot': 'Drop',
    'DualMedia Esports': '',
    'Duck Gaming': 'Duck',
    'Dylema Gaming': 'Dyle',
    'E-Natolian Sports Club F': 'E-Na',
    'E-Xolos LAZER': 'EXL',
    'E2S Lexious': 'E2S',
    'E9Sports': 'E9',
    'ECM FCG eSports': 'FCG',
    'EDward Gaming': 'EDG',
    'EFuture': 'EF',
    'EGN Esports': 'EGN',
    'EGO': 'EGO',
    'EGO Media': 'EGOM',
    'ELNiS Esports': 'DRX',
    'EMPEROR': 'EMPE',
    'ESTEVANDOR': 'ESTE',
    'ESTONOESUNJUEGOVALE': 'ESTO',
    'ETERNAL': 'ETER',
    'EXCEL': 'XL',
    'EXEN Esports': 'EXEN',
    'EXO Clan': 'EXO',
    'EZ KATKA': '',
    'EZBake Clan': 'EZBa',
    'EZPZ': 'EZPZ',
    'East Hill': 'East',
    'Eazy One Gaming': 'EZ1',
    'Echo 8': 'Echo',
    'Echo Alternative': 'Echo',
    'Eclectiq': 'Ecle',
    'Edelweiss Esports': 'EDW',
    'Einheit': 'Einh',
    'Elemental Esports': 'AR',
    'Elevate': 'ELV',
    'Elevation': 'ELE',
    'Elite': 'Elit',
    'Elmerz Glue': 'Elme',
    'Elo and Muscle': 'EnM',
    'Eloquence': 'ELQ',
    'Elysium': 'Elys',
    'Elysium NOIR': 'Elys',
    'Emerald Gaming': 'EMD',
    'EndGame': 'END',
    'Endavant': 'Enda',
    'Enigma Gaming': 'Enigma',
    'Enterprise Esports': 'EP',
    'Entropiq': 'EIQ',
    'Entropiq Bravo': 'ENTB',
    'Entropy Gaming': 'Entropy',
    'Envy': 'NV',
    'Epherium': 'Ephe',
    'Equality': 'Equa',
    'Equinox Day': 'Equi',
    'Equinox Esports': 'NOX',
    'Equipe': 'Bong',
    'Eros': 'BBG',
    'Eshays': 'Esha',
    'Estral Esports': 'Estral',
    'Eternal': 'Eter',
    'Eternal Fire': 'EF',
    'Eternal Zen Gaming': 'EZG',
    'Eternity Esports': 'DV',
    'EthanK Fan Club': 'SEN',
    'Ethereal': 'Ethe',
    'Euphoria': 'EPA',
    'Europe Savios': 'Euro',
    'Event Horizon': 'EvH',
    'Evil Geniuses': 'EG',
    'Ex-Dallas Vendetta': 'Ex-D',
    'ExPandable': 'GEN',
    'Exality': 'Exy',
    'Exalted Esports': 'EXS',
    'Exceeli Esports': 'XLE',
    'Excel': 'Exce',
    'Excelsa': 'Exce',
    'Exceptis': 'Exce',
    'ExiLe Gaming': 'ExiL',
    'Exodus': 'Exodus',
    'Exorcist.ESC': 'Exor',
    'Exotic': 'Exot',
    'Exsto Gaming': 'ExG',
    'Extenzy Gaming': 'EXZ',
    'F1LS Esports': 'F1LS',
    'F4K Ladies': 'F4K',
    'F4Q': 'F4Q',
    'F5': 'F5',
    'FA': 'DRX',
    'FABRIKEN': 'FABR',
    'FAKEZIN': 'FAKE',
    'FALTAM 2 MIN': 'FALT',
    'FARESHI': 'FRSH',
    'FARMERS': 'FARM',
    'FAV gaming': 'FAV',
    'FBM': 'FBM',
    'FC ': 'FC',
    'FC Pat Patrouille': '',
    'FDP Login': 'FDP',
    'FEARUS': 'FEAR',
    'FENNEL': 'FL',
    'FFQ': 'FFQ',
    'FFT': 'FFT',
    'FIRST Gaming': 'FG',
    'FIU': 'C9W',
    'FIU Valorant': 'FIU',
    'FIU(FIU)': 'FIU',
    'FLICKBAITERS': 'FB',
    'FLu Esports': 'DZ',
    'FOGUETE': 'FOGU',
    'FOXNGAME Esports': 'FOX',
    'FPL-C': 'FPL-',
    'FREEAGENTS': 'FREE',
    'FREELO': 'FREE',
    'FS Esports ': 'FS',
    'FS Gaming': 'EF',
    'FTG Esports': 'FTG',
    'FTW Esports': 'FTW',
    'FTW Fade': 'FTW',
    'FUG': 'FUG',
    'FULL SENSE': 'FS',
    'FULLCS': 'FULL',
    'FUNSNATCHERS': 'FS',
    'FURIA': 'FUR',
    'FURY': 'FURY',
    'FUSCA AZUL': 'FUSC',
    'FW Esports': 'FW',
    'FYB v2': 'Ange',
    'FaZe Clan': 'FaZe',
    'Fadee Gaming': 'AX',
    'Fakezin de cria': 'Fake',
    'Falkol eSports': 'FKL',
    'Fallen5': 'F5',
    'Fancy United Esports': 'FU',
    'Far East Society': 'FES',
    'Fast Rush': 'FR',
    'Fatality': 'DWG',
    'FeaFeaFea': 'Fea',
    'Fear Legends': 'FL',
    'FearSlay': 'EXZ',
    'Fearless': 'Fear',
    'Feel So Good': 'Feel',
    'Feeling': 'FEL',
    'Feint Gaming': 'Fein',
    'Fekyx Esports': 'Feky',
    'Fenerbahçe Esports': 'FB',
    'Fenrir': 'FNR',
    'Ferrari Peek': 'Ferr',
    'Fiat Lux': 'FR',
    'FiftyOne': 'Fift',
    'Fighting 4 Freedom': 'F4F',
    'Fire Angels': 'Fire',
    'Fire Flux Esports': 'FF',
    'Fire Flux Esports Female': 'FF',
    'Fire Flux Young': 'Fire',
    'Fire in the hole(ex-Giants Gaming)': 'ex-G',
    'FireBaby Esports': 'F5',
    'FishkaVTom': 'FVT',
    'Five Ace e-Sports': 'FA',
    'FlamexSerenity': 'Flam',
    'Flash and Dash': 'FD',
    'FlashDash': 'ACE',
    'Flat White': 'Curs',
    'Flayn eSports(HSDIRR)': 'HSDI',
    'Flow State': 'FS',
    'Fluid Gaming': 'Flui',
    'FlyMatez': 'FlyM',
    'FlyToMoon': 'FTM',
    'Flying Pigs': 'SQ',
    'Fnatic': 'FNC',
    'Folouers Esports': 'BD',
    'FontanerosMaura': '19',
    'Food Eat': 'Food',
    'Fordon Boars': 'FB',
    'Fortnite Fraggers': 'FF',
    'Fox Gaming': 'FOX',
    'Fox Wizards': 'FKL',
    'Foxera & Friends': 'Foxe',
    'Foxy': 'Foxy',
    'Foxy Araikordai': 'FXG',
    'Frag Ya Bag': 'Frag',
    'FragHunters': 'Frag',
    'Frail Males': 'Frai',
    'Frat3rnity': 'FF',
    'Free Agents': '',
    'Free Sign': 'Free',
    'French Frogs': 'FF',
    'FrenzyGoKill': 'FGK',
    'Frick Ya Bag': 'FYB',
    'Friendlings': 'FL',
    'Friendlyfire': 'Chat',
    'Frigid': 'FRGD',
    'Froggers': 'Frog',
    'Frontline Esports': 'Fron',
    'Frostwolf': 'FW',
    'FroztFire': 'FG',
    'FuelCore': 'FC',
    'Fulcrum Esports Catalyst': 'FEC',
    'Full Flashed': 'FF',
    'Full Focus': 'Full',
    'FunPlus Phoenix': 'FPX',
    'Funcrew': 'FC',
    'Funee Monkee': 'Fune',
    'Funkboings': 'FNK',
    'Funky Monkeys': 'fM',
    'Furacão BLACK': 'FRB',
    'Furacão RED': 'FAKE',
    'Furious Gaming': 'FG',
    'Furore Draco': 'FD',
    'Fusion Fraggers': 'FF',
    'Futbolist': 'FTBL',
    'Futbolist Female': 'Futb',
    'G.Gang': 'G.G',
    'G2 Esports': 'G2',
    'G2 Gozen': 'G2',
    'G2G Esport': 'G2G',
    'GAMAX eSports': 'BB',
    'GBP Esports': 'GBP',
    'GCU Esports': 'GCU',
    'GD Esports Club': '',
    'GGamDira': 'GGam',
    'GGmate': 'GGma',
    'GIVENCHY PARIS': 'END',
    'GMT Esports': 'GMT',
    'GODSENT': 'GODS',
    'GOMA': 'GMG',
    'GOODFOR1 ': 'GOOD',
    'GRANIT GAMING': 'GRG',
    'GRAZHtAS': 'GRAZ',
    'GVNG': 'GVN',
    'GX3': 'GX3',
    'Galakticos': 'GAL',
    'Galakticos Sirens': 'Gala',
    'Galatics Esports(ehehxd)': 'xd',
    'Galaxy': 'FKL',
    'Galaxy Carrots': 'Gala',
    'Galaxy Racer': 'GXR',
    'Galaxy Racer Female': 'GXR',
    'Gambit Esports': 'GMB',
    'GameAgents': 'GA',
    'Gamelanders Blue': 'GLB',
    'Gamelanders Purple': 'GLP',
    'Gamer In Real Life': 'FF',
    'GamerDuderGuys': 'Game',
    'Gamerbots': 'GB',
    'Gamers of Future': 'GOF',
    'Gaming Barracks': 'Gami',
    'Gaming Team SELECTOR': 'GTS',
    'Gangue do Fra(Squad5)': 'DLWZK',
    'Geekay Esports': 'GK',
    'Gehenna Sweepers': 'GHS',
    'Geko Geko': 'Geko',
    'Gen.G': 'GEN',
    'Gen.G Black': 'GGB',
    'Genesis': 'GEN',
    'Genuine Gaming': 'GG',
    'Ghost CommandoS': 'GCS',
    'Ghost Gaming': 'Ghost',
    'GhostFamily E-Sports': 'Ghos',
    'Giants G4E': 'Gian',
    'Giants Gaming': 'GIA',
    'GiefKalash': 'Gief',
    'Gifted': 'Gift',
    'Global Esports': 'GE',
    'Go next': 'GN',
    'GoAhead': 'Avoc',
    'GoNGo Prince': 'GNG',
    'Goats and Glory': 'Goat',
    'Goblin Squadron': 'GS',
    'GochuGaru': 'CHU',
    'God Given': 'God',
    'God Particles': 'GP',
    'God Squad(ex-EXO Clan)': 'ex-EXO',
    'GodLAN': 'GodL',
    'GodVibes': 'GV',
    'Godalions': 'GIA',
    'Godlike Esports': 'GodL',
    'Godset': 'EG',
    'Goldencat Gaming': 'Gold',
    'Gonzo Gaming': 'Gonz',
    'Good Fellas': 'GF',
    'Good Game': 'Good',
    'GoodVibes': 'GV',
    'Goodfellas Gaming': 'GFS',
    'Goofy Goobers': 'GG',
    'GrandSpirit': 'Gran',
    'Granjeros': 'Gran',
    'Grapefruit Techniques': 'GT',
    'Gravitas': 'GRV',
    'Graviton Surge': 'GS',
    'Green beans': 'Gree',
    'Griffin E-Sports': 'GFN',
    'Griffos Starfire': 'Grif',
    'Grilled Cheese': 'Gril',
    'Grimz Esports': 'BME',
    'Grinch Gang': 'GG',
    'Grind City': 'GC',
    'Ground Zero': 'GZ',
    'Grow uP eSports': 'uP',
    'Guardian Esports Team': 'GD',
    'Guess': 'Guess',
    'Guild Esports': 'GUILD',
    'Guild X': 'GUILD',
    'GunTeR': 'GTR',
    'GunsForHire': 'Guns',
    'Gunslingers': 'Guns',
    'Gydom Galva': 'GG',
    'HARD Esports': '9z',
    'HATALANTE': 'AG',
    'HE Gaming': 'HG',
    'HEAD HUNTERS': 'EG',
    'HEET': 'HEET',
    'HEET RED': 'HEET',
    'HERO Esports': 'HERO',
    'HG': 'HG',
    'HIGHPOWER': 'hPw',
    'HOIIIIYAH': 'BF',
    'HOMELESS': 'HOME',
    'HONK': 'HONK',
    'HSDIRR': 'HSDI',
    'HaZe Clan': 'HaZe',
    'Hajty': 'Hajty',
    'HalfBliss': 'Half',
    'Hamboigas': 'GX3',
    'Hamtori ZunDeZinx': 'HAM',
    'Hamtories': 'Hamt',
    'Hashira': 'Hash',
    'Hayal Sahnesi Goddess': 'Haya',
    'Hazmat.gg': 'HzT',
    'Headshot': 'Head',
    'Headshot Percentage': 'HSP',
    'Helios Gaming': 'Heli',
    'Hello Kity': 'HK',
    'Hexad': 'HX',
    'Highground': '',
    'HitReg': 'HitR',
    'Hoax': 'BBG',
    'Hollywood Hooliganz': 'HH',
    'Homeless': 'H/L',
    'Homies Nexus': 'FEAR',
    'Hope': 'HOPE',
    'HorizonGG': 'HGG',
    'Hot Thots': 'Frag',
    'HotThots': '100T',
    'Huat Zai': 'HZ',
    'Hugh Jass Construction': 'Hugh',
    'Hydrated': 'HYDRA',
    'HypHypHyp': 'HyP',
    'Hysteria': 'Hyst',
    'I need Girlfriend': 'InG',
    'IC9': 'IC9',
    'IDDQD v2': 'IDDQD',
    'IGNIS Esports': 'IGNIS',
    'ILG JADE': 'GGB',
    'INS4NE': 'INS4',
    'INTZ Angels': 'ITZA',
    'IQ White': '',
    'ISOL-BULIL': 'IB',
    'ISOL-BULIL(VISU Gaming)': 'Quic',
    'ITALIANO': 'ITAL',
    'IVY': 'IVY',
    'Icarus': 'Icar',
    'Ice Donuts': 'ELQ',
    'IceWolves Esports': 'Mega',
    'Icicle Conflict': 'GTS',
    'Iconic': 'Icon',
    'Icons': 'Icon',
    'Ignite': 'IGN',
    'Illinois Servers Please': 'ISP',
    'IlluZion': 'IluZ',
    'Illuminar Gaming': 'IHG',
    'Illusion': '',
    'Illuzion Black': 'Illu',
    'Illuzion Orange': 'Illu',
    'Illés Akadémia Spirit': 'IAS',
    'Iluz(Temp name)': 'EG',
    'Immortals': 'IMT',
    'Imperial Esports': 'IMP',
    'Imposto é Roubo': 'FAKE',
    'Improve Female': 'Impr',
    'In The Lab': '',
    'InControlNation': 'InCo',
    'InFernal': 'FFT',
    'Inertia': '',
    'InetGamer': 'Inet',
    'Infamous Gaming': '9z',
    'Infantry': 'Infa',
    'Infer Esports(Aim.Attack)': 'AMT',
    'Inferno': 'INF',
    'Infinite Esports': 'Infi',
    'Infinity Esports': 'INF',
    'Ingaming': 'Inga',
    'Injected Sheesh': 'Inje',
    'InnerVoice': 'IV',
    'Innocent Cats Esports': 'ICE',
    'Inside Games': 'iG',
    'Insight': 'Insi',
    'Insomnia': 'INSM',
    'Intel New Indians': 'FF',
    'Intense Gaming': 'INT',
    'Intensity': 'GEN',
    'Interstate 95': 'Inte',
    'Intrepid Fox': 'IF',
    'Invaders': 'GEN',
    'Invicta': 'Empire',
    'Invicta Gaming': 'IG',
    'Invictus Gaming': 'iG',
    'Invictus Gaming Academy': 'IG',
    'Invincible Gaming': 'iNv',
    'Istanbul Wildcats Female': 'Ista',
    'Italian Hope': 'IH',
    'JG and friends': '',
    'JG.JIANG': 'JG.J',
    'JMNY6': 'JMNY',
    'JSD': '',
    'Jacked Gamers': 'Jack',
    'Jaguares Esports': 'JGG',
    'Jaguares Fem': 'Jagu',
    'Janus Esports': 'JNS',
    'Java PR': 'RNG',
    'Jays Finest': 'Jays',
    'Je t\'aime de ouf': 'Jt',
    'Jeremiah': 'JH',
    'Jesfrelho': 'Jesf',
    'John Howard': 'JH',
    'Jujutsu': 'Juju',
    'Just Breathe': 'JB',
    'Just happy to be here': 'Anim',
    'JustLose': 'JL',
    'JustSoldiers': 'Just',
    'Juul Team 6': 'Juul',
    'K/D Fixers': 'K/D',
    'K1CK': 'K1CK',
    'KABAHbl': 'AERI',
    'KASTIRALIS': 'KAST',
    'KDA': 'KDA',
    'KG Network': 'KG',
    'KGA': 'KGA',
    'KHABHAT GAMING': 'KG',
    'KILOISDEAD': 'KILO',
    'KINGSLAYERS': 'KS',
    'KJC eSports': 'KJC',
    'KK VALORANT': '',
    'KLATWA': 'KLAT',
    'KONE': 'KONE',
    'KOUD’KOUTO': 'KOUD',
    'KOVA': 'KOVA',
    'KPC Computer Studio': 'KPC',
    'KPI Gaming': 'KPI',
    'KRÜ Esports': 'KRÜ',
    'Kafalar eSports': 'KFLR',
    'KaiXin Esports': 'KX',
    'Kaizen Esports': 'KZN',
    'Kakaopulver': 'DRM',
    'Kalash': 'GMB',
    'Kamil Klein new chapter': 'KAML',
    'Kanga Esports': 'KNG',
    'Kantic Gaming': 'Kantic',
    'Kaos Latin Gamers': 'Kaos',
    'KappaPride': '2G4L',
    'Karma': 'KGG',
    'Kaster Onez': 'Kast',
    'Kawaii': 'Kawa',
    'Keyd Stars': 'VK',
    'Keyd Stars Athenas': 'VK',
    'Kikados da Galaxy Carrots': 'Kika',
    'Kinetic': '',
    'King of Gamers': 'KoG',
    'King\'s Gambit': '19',
    'Kingsmen': 'KGM',
    'Klaus': 'KU',
    'Knights': 'PK',
    'Knights Academy': 'PK.A',
    'Knights of Bizertin Rise': 'EXS',
    'KnockOut Esports': 'BB',
    'Kolossus Academy': 'HEET',
    'Kooky Koalas ': 'KK',
    'Kowareta': 'Kowa',
    'Kraken': 'ITAL',
    'Kraken ESC White': 'KESC',
    'Ksenox': 'Ksen',
    'Kudos': 'KUDO',
    'Kum Gaming': 'Kum',
    'Kungarna': 'KNG',
    'Květinky': 'KVT',
    'L\'institut': 'INST',
    'L8R Bot': 'L8R',
    'LAETUS Gaming': 'BD',
    'LAG Gaming': 'LAG',
    'LAGOS': 'LAGO',
    'LANCHILLERS': 'LANC',
    'LAPFAP': 'LAPF',
    'LBS Esports': 'LBS',
    'LDM Esports': 'LDM',
    'LDN UTD': 'LDN',
    'LE GAMING': '',
    'LEGENDs': 'LDS',
    'LEMONn': 'LEMO',
    'LFS': 'DRX',
    'LFT': 'DRX',
    'LFTval': 'LFTv',
    'LGD Gaming': 'RNG',
    'LGI': 'TSM',
    'LINGUISALESS': 'Gala',
    'LITHUANIAN UNITED': 'LITH',
    'LIZHI': 'LIZHI',
    'LJG': 'LJG',
    'LOL': 'LOL',
    'LOS VAGOS': 'EIQ',
    'LOVEBUG': 'FAKE',
    'LP33': 'LP',
    'LT': 'LT',
    'LUJAika': '',
    'LULw': 'LULw',
    'LUNARISs': 'FNST',
    'LUNÈ Girls Gaming': 'LUNÈ',
    'LYNX TH': 'LYX',
    'La Familia': '',
    'La7zag Esports': '7sg',
    'Lanboken': 'iPon',
    'Langit9': 'L9',
    'Lankräm': 'Lank',
    'Lapki': 'Lapk',
    'Lariox Esports': 'Guns',
    'Las Palmas Unity': 'GIA',
    'Las Vegas Inferno': 'LVI',
    'Las Venturas': 'Las',
    'Lasagna Beam': 'LB',
    'Last Dance': 'LD',
    'Last Minute': 'LT',
    'Last Minute Heroes': 'smok',
    'Last Round Save': 'LRS',
    'Lazarus': 'Laza',
    'Leftovers': 'Left',
    'Legacy Esports': 'LGC',
    'Legendary Donkey Destroyers': 'Lege',
    'Legion': 'LE',
    'Legion de Reconocimiento': 'Cruz',
    'Lemonade Stand': 'LMND',
    'Lenny Time': 'LT',
    'Lenovo Legion Honvéd': 'LLH',
    'Les Braqueurs': 'LB',
    'Les Farmers': 'FKL',
    'Les Zinzins De Lespace': 'ZDL',
    'Lethal Esports Alpha': 'GE',
    'Lethal Grinders': 'L3G',
    'Level 5': 'Lvl5',
    'Leviatán': 'LEV',
    'Levitate': 'Levi',
    'Lexious Gaming': 'LG',
    'Liberty ': 'LBRTY',
    'Liberty Female': 'LF',
    'Liga Uncharted': 'Liga',
    'Lightailty': 'EZPZ',
    'Lightning': 'LT',
    'LilBabies': 'SHV',
    'Lithium': 'Lith',
    'LividOnes': 'Livi',
    'Lobster Car': 'IMT',
    'Logan Paulers': 'Loga',
    'Looking For Org': 'LFO',
    'Looking For Sponsor': 'Look',
    'Looking for team': 'BLEED',
    'Louvre': 'LVR',
    'LucidX': 'JUP',
    'Lucky Boys': 'Luck',
    'Luminosity': 'LG',
    'Lunaris': 'Luna',
    'Lunatic-Hai': 'LH',
    'Lunch Club': 'Lunc',
    'LvL Up Esport': 'LvL',
    'Lycus Empire': 'Lycu',
    'Lycus Empire Red': 'Lycu',
    'Lycus Empire(EGO BOYZ CLUB)': 'EBC',
    'M1X': 'M1X',
    'M1XXX': 'M1XX',
    'M4LIK': 'M4LIK',
    'MAD Army': 'MA',
    'MAFIOZI': 'MAFI',
    'MAJKL': 'MJKL',
    'MAJSTERSZTYK': 'MSK',
    'MALIBULULE': 'Gian',
    'MAX Esports': 'MAX',
    'MAXD Esports': 'MAXD',
    'MCES': 'MCES',
    'ME CONTRATA': '',
    'MELiNA': 'MELi',
    'MEOGANG': 'Dami',
    'MINUS 149(mercenaries)': 'EIQ',
    'MIRONGA VIRUS': 'MIRO',
    'MIXUP': 'MIXU',
    'MJAOMODE': 'MM',
    'MLC Esports': 'MLC',
    'MNA ESPORTS': 'BBL',
    'MORE Esports': 'MORE',
    'MOTHERBOARD THIEVES': 'MOTH',
    'MOTV': 'MOTV',
    'MRKN': 'HSDI',
    'MROrgless': 'EG',
    'MSR Esport': 'MSR',
    'MTP Esport': 'MTP',
    'MUTANTS': 'AERI',
    'MUTED': 'MUTE',
    'MUYAHO': 'MYH',
    'Macacos Bovinos': 'MB',
    'MackoEsports': 'Mack',
    'Made in Thailand': 'MiTH',
    'Madness': 'MADN',
    'Madrid Rise': 'MADR',
    'Magic Five': 'M5',
    'Magma': 'Magm',
    'Malvinas Gaming': 'Malv',
    'Mama\'s Boys': 'Mama',
    'Mamba Mode Gaming': 'MMG',
    'Man I Love Fwogs': 'MILF',
    'Mandatory': 'MDTY',
    'Mangal': 'Mang',
    'Mantou': 'PRX',
    'Mark Five': 'Vora',
    'Marten Gaming': 'Mart',
    'Massive Physiques': 'VRT',
    'Mattistack': 'Matt',
    'Max Control': 'Max',
    'McBTSMac': 'BTS',
    'McTeam': 'Mc',
    'MeT': 'MeT',
    'Megastitut': 'Mega',
    'Memelanders': 'Meme',
    'Mencari Tempat Berlabuh': 'BTR',
    'MeowMeow': 'FaZe',
    'MercenarieZ': 'Enigma',
    'Merge': 'EP',
    'Merlyn Esports Shine': 'MLS',
    'Merry Men': 'Merr',
    'Meta Gaming': 'Meta',
    'Meta Gaming ': 'Meta',
    'Method2Madness': 'M2M',
    'MiTH.Attitude': 'MiTH',
    'MiTH.Streamer': 'MiTH',
    'Mik0nsDisciple': 'FPX',
    'MinD': 'Futb',
    'Minaweebs Money Crew': 'Mina',
    'Mindfreak': 'MF',
    'Miracles': 'MCS',
    'Mirage(Way 2 French)': 'W2F',
    'MishMash Gaming': 'Mish',
    'Mist Walkers': 'Mist',
    'Mix': 'Mix',
    'Mixery': 'Mixe',
    'MoBuckets': 'EG',
    'Mod-Z': 'Mod-',
    'Momentum Based': 'MB',
    'MoneyTime': 'Mone',
    'Monkey Business': 'MB',
    'Monkey Momentum': 'Monk',
    'Monkey Stars': 'Monk',
    'Moon Raccoons': 'MR',
    'Moon Raccoons Black': 'MRB',
    'Moose Knucklers': 'Moos',
    'MoreBetter': 'LVR',
    'Morning Light': 'ML',
    'Morph Impact': 'MORPH',
    'Morumbi': '19',
    'Moscow 5 Academy': '',
    'Moscow Five jr': 'M5',
    'Most Prolific': 'MP',
    'Motion Team': 'Moti',
    'Movistar Optix': 'MOX',
    'Movistar Riders': 'MRS',
    'Mugiwara': 'Mugi',
    'Mujig 100su': '100su',
    'Mustache Men': 'Frag',
    'Mustang Gaming': 'Mustang',
    'Mystery Inc.': 'Inc.',
    'MystiC': 'Myst',
    'Mystify': 'MYS',
    'Mythicals': 'C9W',
    'N0thing To L0se': 'NTL',
    'N4PAS': 'N4PA',
    'NASR Esports': 'NASR',
    'NBD Esports': 'NBD',
    'NBKS CENTURIONS': 'NBKS',
    'NBP': 'NBP',
    'NC State Esports': '',
    'NEBULAA': 'NEBU',
    'NG.Black': 'NG.B',
    'NMDM': 'FKL',
    'NMG Indigo': 'NMG',
    'NO CONTRACT': '',
    'NO ORG': '',
    'NO ORG ': '',
    'NOM eSports': 'NOM',
    'NONAMERS': 'BBL',
    'NOORG2.0': 'NO2',
    'NORTHEPTION': 'Nth',
    'NOSLEEP': 'NOSL',
    'NOT SNP': 'NSNP',
    'NOTHING2LOSE': 'N2L',
    'NOTRAB': 'NOTB',
    'NOX': 'NOX',
    'NOX Esports': 'NOX',
    'NRG Esports': 'NRG',
    'NSIC': 'NSIC',
    'NTER': 'NTER',
    'NUTURN': 'NU',
    'NVM': 'NVM',
    'NXL LIGAGAME': 'NXLG',
    'NXLG Academy': 'NXLGA',
    'NXP.Aether': 'NXP',
    'Nanashi no Gonbee': '74',
    'Narly Narwhals': 'ABX',
    'Nascent United': 'Ghost',
    'Nasty Ninjas': 'NN',
    'Nation Fan Club': 'NFC',
    'Native 2 Empire': 'AX',
    'Natural Selection': 'KK',
    'Natus Vincere': 'NAVI',
    'Naura': 'Naura',
    'Nebula': 'NEB',
    'Nebula ': 'Nebu',
    'Necrotic Esports': 'Necr',
    'Neebs and Weebs': 'Neeb',
    'Need Sponsor': 'Need',
    'Nemesis': 'Neme',
    'Nerd Emoji': 'Nerd',
    'NerdTown eSport': 'NT',
    'Nerdnecks': 'BLISS',
    'Nester': 'NSR',
    'NeverDone': 'Neve',
    'NeverEndingStory': 'NES',
    'New Order': 'NEO',
    'New World': 'LD',
    'Newstar': 'AUS',
    'Next-Gen(The Mafia)': 'The',
    'Nexus Gaming': 'NxS',
    'Nezuko Gaming': 'Nezu',
    'Nice Cars': 'nCars',
    'Night Wings Gaming': 'NWG',
    'Nightblood Gaming': 'Nigh',
    'Nigma Galaxy': 'NGX',
    'Nigma Galaxy Female': 'ARS',
    'Nihil': 'NIH',
    'Nine Esport': 'GFS',
    'Ninjas in Pyjamas': 'NIP',
    'No Country': '',
    'No Hope Gaming': 'NHG',
    'No Mercy': 'NM',
    'No Org': '',
    'No Org Found': 'NOF',
    'No Pressure': 'NP',
    'No Shot': 'DIG',
    'No Teeth': '',
    'No Witness': 'nW',
    'No2B e-Sports ': 'N2B',
    'NoBordeR': 'Kaos',
    'NoKap': 'NoKa',
    'NoNameG0Ds': 'NoNa',
    'NoNamers': 'NNS',
    'NoPoaching': 'PLS',
    'NoPracc': 'NoPr',
    'Noble': 'NBL',
    'Noble Experience': 'NOX',
    'Noble India': 'Nobl',
    'Noir': 'NOIR',
    'Nomads': 'GMT',
    'NongWaen': 'NW',
    'Noobs With Attitude': 'NWA',
    'Nora-Rengo': 'NR',
    'Not Ready': 'Not',
    'Notick': 'Noti',
    'Novagis Gaming': 'NVG',
    'Novavirtus': 'INST',
    'Noxsports(VASTA Gaming)': 'VASTA',
    'Noxus Pro': 'Noxu',
    'Number One Player': 'NOP',
    'Nutrl': 'Brim',
    'O.O.D.A Loopers': 'O.O.',
    'O2 Gaming': 'O2',
    'OBSRV': 'GFN',
    'ODCINKA V2': 'MM',
    'ODDIK': 'GLB',
    'OG': 'OG',
    'OG Esports': 'OGE',
    'OG4Z': 'OG4Z',
    'OIL': '2G4L',
    'ONIC G': 'ONIC',
    'ONYX Purple': 'GX3',
    'OOKERS': 'OOKE',
    'ORDER': 'ORDER',
    'ORGLESS5': 'OG5',
    'ORO Esports': 'ORO',
    'OS GURI': '',
    'OSKARAVELHO': 'OSKA',
    'OW Refugees': '',
    'OWA OWA': 'OWA',
    'Oasis Gaming': 'OAS',
    'Oasis Gaming Aqua': 'Oasi',
    'Obey Alliance': 'Obey',
    'Obsidian Esports': 'OBSD',
    'Obstacle': 'Obst',
    'Oddyssey': 'COL',
    'Odyssey Atlas': 'Brim',
    'OffLimits': 'OL',
    'Offenders': 'Empire',
    'Offlimits': 'OFF',
    'OhMyGirl': 'OhMy',
    'Old Dudes': 'BBG',
    'OldTownRoad': 'OldT',
    'Omni': 'ROX',
    'On The Way': 'OTW',
    'On Top Soon': '',
    'One Breath Gaming': 'OBG',
    'One Shot Esports': 'OS',
    'Onfire Team': 'FF',
    'Oni Fans': 'Oni',
    'Only One Word': 'OOW',
    'Only-Esports': 'Only',
    'OnlyFriends': 'Only',
    'Onlyfans': 'END',
    'Onslaught Gaming': 'OG',
    'Opportunists': 'OPP',
    'Orange Borange': 'OB',
    'Orbit': 'Orbi',
    'Org Not Found': 'Org',
    'Organic Gamers': 'ABX',
    'Orgles5': 'O5',
    'Orgless': 'OG',
    'Orgless Redux': 'Prospects',
    'Orgless5': 'NORG',
    'Origin Sky': 'Orig',
    'OtherSide': 'OS',
    'OtherSide Blue': 'Othe',
    'OtherSide Rouge': 'Othe',
    'OutRage': 'OutR',
    'Outlaws': 'Outl',
    'Outplay Uprising': 'DR',
    'Ovation eSports': 'Ovat',
    'OverPalaStrike': 'OPS',
    'Overt': 'Over',
    'Overtime Esports': 'OTE',
    'Oxxgen Esports': 'OXX',
    'Oxygen Esports': 'OXG',
    'Oxygen Supremacy ': 'O2',
    'PACT': 'PACT',
    'PAJACE': 'PJC',
    'PARA LAZIM': 'PARA',
    'PASSAROS DO AMORS': 'PASS',
    'PATATERA SQUAD': 'MRS',
    'PDHM Gaming': 'PDHM',
    'PEACE': 'PEAC',
    'PENTA': 'PENT',
    'PHARAONS': 'PHAR',
    'PLATOON': 'P2N',
    'PLATOON Belarus': 'PB',
    'PLAYMAKERS': 'PLAY',
    'PM': 'F4Q',
    'POISON CLAN': 'E9',
    'POWER': 'POWER',
    'PROJECT X': 'OTW',
    'PROJECT XY': 'PROJ',
    'PROJEKT RADIANT': 'PR',
    'PROPARTY': 'PP',
    'PSISTORM': 'DZ',
    'PUGSTARS': 'PUGS',
    'PULSAR OLDSTARS': 'PULS',
    'PURPURE': 'PURP',
    'PXL Esports': 'PXL',
    'Palinka': 'Pali',
    'Pana.Rabbit': 'Pana',
    'Panthers Violet': 'Pant',
    'Pants Down': 'PD',
    'Paper Rex': 'PRX',
    'Paradox Esports': 'PRDX',
    'Paraplegic Buffalos': '',
    'Paratroops': 'PARA',
    'Parek v rohliku': 'Pare',
    'Party Stool': 'Part',
    'PartyParrots': 'PP',
    'Pass Gaming': 'PASS',
    'Patchwork': 'PW',
    'Peaky Blankers': 'Peak',
    'Peek Performance': 'Peek',
    'Peeposhy': 'Peep',
    'Pendragon Cyber': 'MDTY',
    'Penguin Sledding': 'PS',
    'Penguins of the night': 'PoNi',
    'Penn State University': 'C9W',
    'PffxD': 'Pffx',
    'Phantom Troupe': 'PT',
    'Phenomenon': 'NNS',
    'Phinance G': 'PGT',
    'Pho Real': 'Pho',
    'Phoenix': 'FA',
    'Phoenix1': 'PHX1',
    'Physical': 'PY',
    'PiP PiP PiP': 'PiP',
    'Pichon Bellaco': 'EXL',
    'Piercer Esports': 'PER',
    'Pigeons Esports': 'PIGE',
    'Pillow': 'PL',
    'Pingu Gang': 'PG',
    'Pioneers': 'KCP',
    'Pirate Nation': 'Pira',
    'Pit Stop': 'PS',
    'Plore Gaming': 'CISF',
    'Pochinki Predators': 'PP',
    'Poco Loco(Eloquence)': 'ELQ',
    'PointAndClick': 'HSDI',
    'Poised': 'C9',
    'Polaris': 'PLR',
    'Polarity Esports': '0.5',
    'Polpette Di Carne': 'Brim',
    'Pon Pon(100 Blifted)': '100B',
    'Predestinados': 'Pred',
    'Premier Esports': 'DIG',
    'Pretty Boyz': 'PBz',
    'Pridestark Empire': 'Akre',
    'Prima Esport': 'EDW',
    'Prinzen von Stuttgart': 'HONK',
    'Prism Esports': 'PRSM',
    'Pro Hub Gaming': 'Pro',
    'Procyon Team': 'Procyon',
    'Prodigy': 'Prod',
    'Professional Malders': 'Prof',
    'Project': 'EG',
    'Project !': 'P!',
    'Project A': 'Proj',
    'Project CORE': 'COL',
    'Project D': 'PD',
    'Project S': 'S',
    'Project SW': 'PSW',
    'Project X': 'Divi',
    'Project02': 'Proj',
    'Prominence': 'PRM',
    'Prophecy ESC': 'Prop',
    'Prospects': 'Prospects',
    'Prospects(Headshot Percentage)': 'HSP',
    'Proven': 'Prov',
    'Proximity': 'EG',
    'Pug Gods': 'OTW',
    'Puggers Unite': 'Pugg',
    'Punitive Force(Rugratz)': 'RUG',
    'Pure': 'NRG',
    'Purple Cobras': 'PC',
    'Pyronic': 'PYR',
    'PÊEK Gaming': 'PÊEK',
    'QConfirm': 'QC',
    'QLASH': 'QLSH',
    'QLASH Egypt': 'NASR',
    'QQQ': 'QQQ',
    'QQQ Hasagi': 'DXG',
    'Qing Jiu Club': 'Q9',
    'Quantum Strikers ': 'QS',
    'Question Mark': 'QSM',
    'Quick Shots': 'Terrific',
    'Quickmath': 'Quic',
    'R!OT Gaming': 'R!OT',
    'RAIJIN': 'RAIJ',
    'RANK G': 'Mina',
    'RARE Esports': 'RARE',
    'RAS': 'MCES',
    'RATVI': 'RATV',
    'RAWR xD': 'RAWR',
    'RD Esports': '',
    'RED Canids': 'RED',
    'RED5': 'R5',
    'REJECT': 'RC',
    'REPLY TOTEM': 'TTM',
    'REVIVE': 'REVI',
    'REVOADINHA': 'SH',
    'RGB Gaming': 'QQQ',
    'RIFLE CRUTCHERS': 'RC',
    'RIT Orange': 'EG',
    'ROC Team': 'MiTH',
    'ROG Academy': 'ROG',
    'ROG Esport': 'ROG',
    'ROLO COMPRESSOR': 'Rise',
    'ROX TEAM': 'ROX',
    'RTG eSports': 'RAAD',
    'RVNS Esports': 'RVNS',
    'RYU Gaming ': 'RYU',
    'Radiance': 'RAD',
    'Radiant Esports': 'Radi',
    'Radiant Roombas': 'LVI',
    'Rainbow7': 'KZN',
    'RainbowMind': 'RbM',
    'Raise Your Edge': 'RYE',
    'Ranked Stars': 'RS',
    'Rated Gaming': 'Rate',
    'Rating Greatly Decreased': 'ES',
    'Reality Rift': 'RR',
    'Rebellious Gaming': 'SANE',
    'Rebels Gaming': 'RBLS',
    'Rebirth Esports': 'RE',
    'Reborn': 'Rebo',
    'Reckless Lads': 'RL',
    'Reckoning Esports': 'RGE',
    'Recon 5': 'Reco',
    'Red Hot': 'Red',
    'RedFire.Wasd Arena': 'LE',
    'Redragon': 'Redr',
    'Redteam Esport': 'Redt',
    'Reformados': 'AUR',
    'Reformed': 'RFD',
    'Regal E-Sports': 'Enigma',
    'Regnum Carya Esports': 'REG',
    'Reject$': 'R$',
    'Remember Me': 'RM',
    'Renaissance': 'OXX',
    'Renatus Black': 'RTS',
    'Renatus White': 'RTS',
    'Renegades': 'RNG',
    'Resonate': 'RESO',
    'Resurgence': 'Resu',
    'Resurrection Sickness': 'Resu',
    'Retake': 'FaZe',
    'RevX Necrosis': 'RevX',
    'Reven Esports': 'Reve',
    'RevoadaVLR': 'Revo',
    'Revolution': 'oveR',
    'Rex Regum Qeon': 'RRQ',
    'Rexpect eSports': 'Rexp',
    'Rhyno Esports': 'Rhyn',
    'Rice Burrito': 'Rice',
    'Rio Company': 'RIO',
    'RipNTear': 'RNT',
    'Rise': 'Rise',
    'Rise Gaming': 'Rise',
    'Rix.GG': 'RixGG',
    'Rix.GG Lightning': 'RIX',
    'Rix.GG Thunder': 'RIX',
    'Rock Bottom': 'RB',
    'Rodelindo Roman esports': 'Procyon',
    'Roosters': 'ROO',
    'RosCey eSports': 'ALLW',
    'Rose': 'Rose',
    'Rover': 'Rove',
    'Royal Never Give Up': 'RNG',
    'Royals': 'Roya',
    'Rugrats': 'Rugr',
    'Rugratz': 'RUG',
    'Run it Back': 'FG',
    'RunDownMid': 'PRX',
    'Running Dogs': 'NoKa',
    'Ryze Gaming': 'Ryze',
    'S2': 'TI',
    'S2K': 'S2K',
    'S2V Esports': 'S2V',
    'S8UL Esports': 'S8UL',
    'SAKS': 'O5',
    'SALOH': 'PULS',
    'SAW': 'SAW',
    'SBTC Esports': 'SBTC',
    'SCARZ': 'SZ',
    'SCYTES Esports': 'Majesty',
    'SE ATLAS': 'SE',
    'SEMORGAINDA': 'SEMO',
    'SENTHEX': 'BIG',
    'SETOUCHI ENLIFE': 'STCE',
    'SFG': 'COL',
    'SHHHHHHH!': 'SHHH',
    'SHOOT FOR FUN': 'FU',
    'SHORTYKINGS': 'C9',
    'SIGN US': '',
    'SIZDIM BEKLE': 'BBL',
    'SKADE': 'SKD',
    'SLAMMING GEARS': 'SG',
    'SLICK': 'SLK',
    'SLO': 'SLO',
    'SLU Esports': 'IMT',
    'SMARACIS eSports': 'SES',
    'SMARACIS eSports Female': 'SES',
    'SOR': 'SOR',
    'SPARX Esports': 'SPAR',
    'SPEAR GAMING': 'SPG',
    'SR KADILIMAN': 'KDM',
    'STAGA': 'STAGA',
    'STELLAR': 'STEL',
    'STORM': 'IMT',
    'STR99': 'STR99',
    'STREET SHARKS': 'STRE',
    'SUMMIT\'s 탁아소': 'LH',
    'SUMN FC': 'SUMN',
    'SUPER SQUAD': 'SUPE',
    'SUPERFLY': 'SF',
    'SUPRMODE Gaming': 'SUPR',
    'SUS SquaD': 'Flam',
    'SV Empire': 'SV',
    'Saber': 'SQ',
    'Sac State Hornets': 'Sac',
    'Sad Girls': 'Sad',
    'Sailor Scouts': 'SS',
    'Saints': 'PRX',
    'Sakura Storm': 'SS',
    'Salt Esports': 'SALT',
    'Salt and Vinegar': 'Salt',
    'Samurai Esports': 'SE',
    'Sanctity': 'Sanc',
    'Sandwich Eaters 40': 'RNG',
    'Sangal Esports': 'SE',
    'Santiago Wanderers': 'SW',
    'Santino': 'AE',
    'Saplak': 'KFLR',
    'Sausage Party': 'FNST',
    'Saviors': 'HAM',
    'Sbread Gaming': 'Sbre',
    'Schat\'z': 'FF',
    'Seal Team 6': 'SEAL6',
    'Second Wind': 'SW',
    'Sector One': 'Sect',
    'Sedated': 'Seda',
    'Seeker': 'SEEK',
    'Seeker Esports': 'SEEK',
    'SeekingContract': '',
    'Sekai': 'Seka',
    'Sengoku Gaming': 'SGG',
    'Seniman Grooming': 'S8v',
    'Sentinels': 'SEN',
    'SeolHaeOne Prince': 'SP',
    'Sequenz': 'Sequ',
    'Serenity': 'SRN',
    'Serenity Black': 'SRN',
    'Serenity Purple': 'SRN.P',
    'Sewercats': 'Sewe',
    'Shadow Life': 'SL',
    'Shadownet': 'SN',
    'ShadowzGG V2': 'SKD',
    'ShanXi Gaming': 'SXG',
    'ShanXi Gaming Girls': 'SXG',
    'Sharks Esports': 'SHK',
    'Sharp-Clan': 'Sharp',
    'Sharper Esport': 'SP',
    'Shaverma': 'Shav',
    'Shawty Gamin\'': 'Shaw',
    'Shi Shui Wen': 'SSW',
    'Shiba': 'Shib',
    'Shidiots': 'SHID',
    'ShikouKouketsu': 'SK',
    'Shingeki No Kyojin': 'Shin',
    'Shironeko': 'C7',
    'ShockDart': 'RYE',
    'Shoguns': 'DIG',
    'Shopify Rebellion': 'SR',
    'Showstoppers': 'Show',
    'Sicko Mode': 'Sick',
    'SimpleMinecraftPlayers': 'Simp',
    'Simplicity Gaming': 'EXS',
    'Sinfvl': 'TSM',
    'Six Karma': '6K',
    'Sk8tr Boyz': 'Sk8',
    'Skelp Esports': 'XL',
    'Skull Cracker': 'SKC',
    'Slaughter House': 'NBL',
    'Slimy Boogermen': 'SLMY',
    'Smaracis Esports(FlyToMoon)': 'FTM',
    'Smooth Criminals': 'FFQ',
    'Sneaker Daily Meloner': 'SDM',
    'Snowmen': 'SNOW',
    'SoaR': 'SoaR',
    'Soabh': 'CAG',
    'Socks Up': 'Sock',
    'Socks up Nyx': 'Sock',
    'Solar': 'KK',
    'Somalia': 'Soma',
    'Somnium Esports': 'BME',
    'Soniqs': 'SQ',
    'Souldazz': 'Soul',
    'South Built Esports': 'SBE',
    'South East Movement': 'FaZe',
    'Sovereign': 'NV',
    'Space Bound': 'SQ',
    'Space Cowboys': 'Spac',
    'Spacestation Gaming': 'SSG',
    'Spain+China+Africa': 'CE',
    'Spain.dll': 'ES',
    'Spanish Leftovers': 'GIA',
    'Spanish Mix': 'OG',
    'Spectral': 'Spec',
    'Spectral Esports Blue': 'Spec',
    'Spectral Esports Purple': 'Spec',
    'Spot Up': 'SUP',
    'Spotlight': 'SPL',
    'Sprayz Gaming': 'SzG',
    'Squad5': 'S5',
    'Squirtle Squad': 'Squi',
    'Squishy and Friends': 'Akre',
    'Stampede Gaming': 'Stam',
    'StarlessGG': 'Star',
    'Stars': 'OPP',
    'Stars Horizon': 'SH',
    'Stars Horizon Fem': 'SH',
    'Stars Horizon Vênus': 'SHV',
    'StartedFromCS': 'SFCS',
    'Steal Your Glory': 'SYG',
    'Stealth': 'SQ',
    'Steel Tactics': 'OXG',
    'Stim Beacon Boyz': 'Stim',
    'Storks Phalanx': 'SPX',
    'Straight Outta The Zoo': 'SOTZ',
    'Straight Warfare': 'Stra',
    'Stunned5': 'S5',
    'Stuverance Esport': 'Mega',
    'Sum 2 Prove': 'S2P',
    'SunSister Rapid': 'SS-R',
    'SunSparks': 'SS',
    'Suning Gaming': 'SN',
    'Super Weenie Hut Jr\'s': 'Rise',
    'SuperMassive Blaze': 'SMB',
    'SuperStars': 'Supe',
    'Superdomineering': 'OOW',
    'Supermassive Blaze Female': 'SMBF',
    'Supremacy Gaming': 'SG',
    'Suradech Gaming': 'SDG',
    'Surreal Esports': 'Surr',
    'Swag Silicone': 'SS',
    'Swagoi': 'ABX',
    'SwayGG': 'ABX',
    'SwedishStyle': 'BD',
    'Synergy': 'SYN',
    'Synergy Esports': 'Syne',
    'Synthetic(Fortnite Fraggers)': 'FF',
    'T1': 'T1',
    'T1 Academy': 'T1A',
    'T1 Korea': 'T1KR',
    'T69': 'T69',
    'TAMU Maroon': 'FaZe',
    'TC Arise': 'ARS',
    'TEMPO': 'PS',
    'TENSTAR': 'TEN',
    'TENSTAR Nova': 'TEN',
    'TERROR.NET': 'TNET',
    'TGPA': 'FA',
    'TGS aXe': 'TGS',
    'THANATOS': 'GXR',
    'THE FIVE EMPERORS': '100T',
    'THE ORIGINALS': 'ORG',
    'THE SHABLES': 'SBL',
    'THE START W': 'TSW',
    'THEX': 'THEX',
    'THOSE GUYS': 'TG',
    'TIMETOPLAY': 'TTP',
    'TLP & Friends': 'PROJ',
    'TLP Monkies': 'TLP.M',
    'TNL Esports': 'TNL',
    'TOOOLS esports': 'TOOOLS',
    'TRAITORS': 'TTS',
    'TRAMPET': 'TRAM',
    'TRAUMA': 'TRAU',
    'TREMBALA': 'TREM',
    'TSM': 'TSM',
    'TSM Academy': 'TSM.A',
    'TSM X': 'TSM.X',
    'TT willhaben(ZEITGEIST)': 'ZEIT',
    'TTSH': 'TTSH',
    'TUBEPLE Gaming': 'TBP',
    'TUMT': 'TUMT',
    'TYLOO': 'RNG',
    'TYPHOONS': 'TFN',
    'Table for 5': 'Tabl',
    'Tactical Five': 'Tact',
    'Taipan Esports': 'NRG',
    'Take Flyte': 'TF',
    'Take It Easy': 'MEAP',
    'Tale Quale': 'TQL',
    'Tales of Eastern': 'TOE',
    'Tarren Mill': 'TM',
    'TauCeti': 'TCE',
    'Taunt': 'TL',
    'Teal Seam': 'TS',
    'Team 28': '28',
    'Team 2D': '2D',
    'Team 600': '600',
    'Team 7AM': '7AM',
    'Team ANGE1': 'Team',
    'Team Aceu': 'IMT',
    'Team AlpTV': '',
    'Team Ancients Female': 'N2L',
    'Team Anomaly(9XL)': '',
    'Team Arrow': 'Arrow',
    'Team AsLanM4shadoW': 'AsLan',
    'Team Assent': 'Team',
    'Team Asteria': 'IGN',
    'Team Aurora': 'AUR',
    'Team Austin Creed': 'ASC',
    'Team BDS': 'BDS',
    'Team BELEAGUERS': 'FOX',
    'Team BRNWOWZK1': 'BRN',
    'Team Bachara': 'TH',
    'Team Basilisk': 'TB',
    'Team Benelux': 'BNLX',
    'Team Big BAAM': 'BAAM',
    'Team Bliss': 'BLISS',
    'Team Brax(T1)': 'T1',
    'Team CDNThe3rd': 'CDN',
    'Team CIS': 'CIS',
    'Team Calango': 'Team',
    'Team Capalot': 'CAP',
    'Team Clutch_Fii': 'CLU',
    'Team Cohesion': 'Team',
    'Team Crushed': 'CRUSH',
    'Team Cyanide': 'CYA',
    'Team DACH': 'DACH',
    'Team Davidp': 'Dp',
    'Team Demiral Esports': 'FB',
    'Team Diamond.R': 'Team',
    'Team Doggo': 'TD',
    'Team Duelist': 'Duel',
    'Team Duno(Worst Players)': 'DC',
    'Team DylanteroLIVE': 'DYL',
    'Team ETT': 'OBG',
    'Team Eastern Europe': 'EE',
    'Team Empire ': 'Empire',
    'Team Ex6TenZ': 'Team',
    'Team Exploit': 'TE',
    'Team FANGS': 'FNG',
    'Team FYB': 'FYB',
    'Team Fearoth': 'Fear',
    'Team Fi': '',
    'Team Fight': 'DIG',
    'Team Finest': 'FNST',
    'Team Finest Female': 'FNST.F',
    'Team Flux': 'FLUX',
    'Team Flux(Spectral Esports Blue)': 'RNG',
    'Team Focus': '19',
    'Team France': 'FR',
    'Team Front': 'GEN',
    'Team GMM': 'CBT',
    'Team Galaga': 'GG',
    'Team Godzilla': 'SHK',
    'Team Gravity': 'GV',
    'Team Happy': 'GOBB',
    'Team Heretics': 'TH',
    'Team Hiko(Gen.G)': 'GEN',
    'Team HyP': 'AsLan',
    'Team Impakt': 'IMP',
    'Team Influencer': 'SNG',
    'Team Invictus (India)': 'INV',
    'Team Italy': 'IT',
    'Team Izak(Fordon Boars)': '',
    'Team JakenbakeLive(Immortals)': 'IMT',
    'Team Jbzz': 'Jbzz',
    'Team Jordan Fisher': 'JF',
    'Team Kephrii': 'TKE',
    'Team Korea': 'KR',
    'Team Kurt': 'Kurt',
    'Team LZ': 'LZ',
    'Team Launch': 'LAUNCH',
    'Team Lightning': 'LNG',
    'Team Liquid': 'TL',
    'Team Liquid R6': 'Cage',
    'Team Lixa': 'Lixa',
    'Team Lothar': 'LOT',
    'Team LuZi': 'Team',
    'Team Lutti(HypHypHyp)': '123',
    'Team Mahi': 'Enigma',
    'Team Majesty': 'Majesty',
    'Team Mang0': 'Mang0',
    'Team Mendo': 'MND',
    'Team Miss Rage': '',
    'Team Mithrain': '',
    'Team Mixwell': 'Team',
    'Team Mixwell(Prodigy)': 'Prod',
    'Team Moon': 'Team',
    'Team Mystic': 'TM',
    'Team Myth(TSM)': 'TSM',
    'Team NAME': 'Team',
    'Team Name': 'TN',
    'Team Ninja(100 Blifted)': '100B',
    'Team NoM': 'NoM',
    'Team NoX': 'NoX',
    'Team Nordics': 'NORD',
    'Team ONSCREEN': 'ONSC',
    'Team Onscreen(fish123)': '123',
    'Team Orb(DREAMCHASERS)': 'DC',
    'Team Owl': 'OWL',
    'Team PAGO3': 'Team',
    'Team Pan': 'Team',
    'Team Paula Nobre': 'PN',
    'Team Plague': 'Team',
    'Team Poland': 'FR',
    'Team Portugal': 'PT',
    'Team Punished': 'Team',
    'Team Q1': 'Shav',
    'Team Queso': 'TQ',
    'Team Questionmark': 'HEET',
    'Team Quitooo': 'Shaw',
    'Team RA\'AD': 'RAAD',
    'Team Reapers': 'AEEC',
    'Team Reckaroo': 'Team',
    'Team RobertoCein': 'ROB',
    'Team Rocket': 'Team',
    'Team Roquette': 'Team',
    'Team RosieRiver': 'RR',
    'Team Rumble': 'HSP',
    'Team Ryux': '',
    'Team SGD': 'SGD',
    'Team SHIFT': 'SHIFT',
    'Team SMG': 'SMG',
    'Team SMOKER': '19',
    'Team Sacy': 'SCY',
    'Team Sampi': 'SMP',
    'Team Samurai': 'TS',
    'Team ScreaM': 'SCRM',
    'Team Secret': 'TS',
    'Team Sfory': '',
    'Team Sh0ts': 'STS',
    'Team Sinful': 'GIA',
    'Team Singapore': 'KR',
    'Team Singularity': 'SNG',
    'Team Singularity Female': 'SNG',
    'Team Skyyart(Washed Players)': 'Wash',
    'Team Solaaaa': 'SOL',
    'Team Solace': 'Team',
    'Team Sonii': 'Sonii',
    'Team Spain': 'ES',
    'Team Spectralis': 'Spectralis',
    'Team Sprel': 'Team',
    'Team StPeach': 'STP',
    'Team Taimou': 'Team',
    'Team Tamilas': 'Tam',
    'Team TenZ(Cloud9)': 'C9',
    'Team Tixinha': 'Team',
    'Team Tom': 'Team',
    'Team Tomorrow BIG(FishkaVTom)': 'FVT',
    'Team Toxic': 'TT',
    'Team Turkey': 'TU',
    'Team UK': 'UK',
    'Team Underrated': 'UR',
    'Team Untold': 'UNT',
    'Team Up': 'Team',
    'Team VS': 'GCS',
    'Team Valkia': 'VLK',
    'Team Valor': 'VL',
    'Team Vikings': 'VKS',
    'Team Vitality': 'VIT',
    'Team Volpid': 'EG',
    'Team Volted': 'TeVo',
    'Team Weibo': 'Weibo',
    'Team White': 'TW',
    'Team X': 'MILF',
    'Team XO': 'XO',
    'Team YamatoN': 'YMT',
    'Team Yelo': 'Team',
    'Team Z': 'LT',
    'Team Zerator': 'ZER',
    'Team Zerator ': 'TZ',
    'Team Zigueira': 'ZIG',
    'Team Znorux': 'ZNO',
    'Team ardiis': 'AsLan',
    'Team blackelespanolito': 'BLA',
    'Team blue_mx': 'BLU',
    'Team bnans': 'BNA',
    'Team bonkar(Ninjas in Pyjamas)': 'NIP',
    'Team cNed': 'cNed',
    'Team dizzy': 'DZY',
    'Team draken': 'Team',
    'Team fl0m': 'FLM',
    'Team gabrielcro': '',
    'Team gamelifeow': 'GAM',
    'Team gdolphn(FABRIKEN)': 'FABR',
    'Team gob b': 'GOBB',
    'Team iaaras2': 'DYL',
    'Team izak': 'Team',
    'Team kalera': 'KAL',
    'Team kennymcc': 'KEN',
    'Team mch': 'MCH',
    'Team mym_alkapone': 'MYM',
    'Team nookyyy': 'NKY',
    'Team oNe': 'oNe',
    'Team ocheon2': '',
    'Team sabagod2': 'SAB',
    'Team unlostv': '',
    'Team vakk': 'vakk',
    'Team wtcN': 'WTC',
    'Team zonixx': '2G4L',
    'Team123': 'Team',
    'Team666': 'Team',
    'Techno Monks': 'TM',
    'Tek Gaming': 'Tek',
    'TempesT': 'TMP',
    'Tenacity Pro': 'LG',
    'Tengkorak': 'OG',
    'Terminate Esports': 'FXG',
    'Thailand Attitude': 'Thai',
    'Thane Peek': 'Than',
    'Thanos Mug Academy(CoT)': 'CoT',
    'Thatoc Esports': 'FTBL',
    'The Better LG': 'The',
    'The Box by Infinity Area': 'TBOX',
    'The Boys': 'TB',
    'The Clappening': 'Clap',
    'The Dush': '',
    'The First Order': 'TFO',
    'The Future': 'The',
    'The Goose House': 'TGH',
    'The Goose House Lunar': '',
    'The Guard': 'GRD',
    'The Infinity Esports': 'INF',
    'The Kor Kors': 'HZ',
    'The Mafia': 'The',
    'The Mafias EAID': 'MORPH',
    'The Mandalorian': 'MAN',
    'The Meaps': 'MEAP',
    'The Noah Aiello': 'SEN',
    'The Panic Team': 'The',
    'The Silk Road': 'SILK',
    'The Stream Team': 'TST',
    'The Unfortunate Five': 'The',
    'TheDuckArmy': 'TheD',
    'ThiccWRECK': 'C9',
    'Third Impact': 'TI',
    'Thrifty': 'Ghost',
    'Thunderbolts Gaming': 'TBG',
    'TiAMAT': 'TiA',
    'Tiimu Sagashitemasu': 'TS',
    'TikTok Baddies': 'TikT',
    'Tilted': 'TILT',
    'Time In': 'TI',
    'Time Out': 'TO',
    'Timing Monster Gaming': 'TMG',
    'TinyTurtles': 'TT',
    'Titan Esports': 'Tita',
    'Title Chasers': 'STEL',
    'Todak': 'TODAK',
    'Toh \'n\' Friends': 'JG.J',
    'TooGoodForLan': '2G4L',
    'TooManyQuestions': 'TMQ',
    'TopHard Esports': 'TH',
    'Totem Providence': 'TTM',
    'Totoro Gaming': 'Totoro',
    'TradeLikePros': 'TLP',
    'TradeLikePros Gold': 'TLPG',
    'TradeLikePros Red': 'TLPR',
    'Trash Pandas': 'Tras',
    'Trees Money Crew': '',
    'Triangle Offense(calclub-p)': 'calc',
    'Trident Clan': 'TC',
    'Trident Esports': 'TRIDENT',
    'Triumphant Song Gaming': 'All',
    'Tropa Suprema': 'TEN',
    'Tropinha do TIKTOK': 'SH',
    'Trouble Makers': 'ISP',
    'True Rippers': 'TR',
    'Try eSports': 'GLP',
    'Turgutlu Belediyesi Esports Ladies': 'G2',
    'Twin Esports': 'PÊEK',
    'Typhoon': 'TP',
    'Tyrant Esports': 'TYR',
    'UBITEAM': 'UBI',
    'UCAM Esports Club': 'UCAM',
    'UCF Valorant': 'FaZe',
    'UCFC Esports': 'AE',
    'ULVL': 'SE',
    'US Army Esports': 'COL',
    'UYU': 'UYU',
    'UnSigned': 'UnSi',
    'Unbind Crouch': 'Unbi',
    'UndeRank': 'UR',
    'Undead Gaming': 'Aion',
    'UnderDogs': 'Unde',
    'UnderDogs Gaming': 'Unde',
    'Underdog': 'Unde',
    'Ungentium': 'A3D',
    'Union Gaming': 'uG',
    'Unique': 'Uniq',
    'Unity Esports': 'Unit',
    'University at Buffalo': 'XSET',
    'Unknown': 'UK',
    'Unknownpros': 'Unkn',
    'Unranked': 'GUILD',
    'Unsigned Losers': 'OPP',
    'Unsold Stuff Gaming': 'SGG',
    'Up For Sale': 'RNG',
    'Up Next': '',
    'Updraft': 'SZ',
    'Urubuzada e-Sports': 'GLB',
    'Uruguay 3': 'Urug',
    'UwU': 'UwU',
    'VAC Kimchi': 'VAC',
    'VASTA Gaming': 'VASTA',
    'VCTRY Esports': 'VCTRY',
    'VECA': 'IVY',
    'VERTEX': 'VRTX',
    'VESPA': 'NV',
    'VETERANOS e-Sports': 'VE',
    'VI VET MEST': 'VVM',
    'VIIIJNIIIIIIIIIIIIIIIIII': 'ABL',
    'VIMDOLOL': 'VIMD',
    'VIRTUOSO': 'VRT',
    'VISU Gaming': 'VISU',
    'VKNATA': 'GLB',
    'VLT Asteria': 'VLT',
    'VPG Headhunters': '',
    'VVS': 'VVS',
    'VVV': 'VVV',
    'VZN': 'VZN',
    'Vacuumers': 'Vacu',
    'Valkyrie': 'SEN',
    'Valorando': 'Valo',
    'Valorantaupe': 'PiP',
    'ValorsGG': 'Valo',
    'Valstars Gaming Female': 'Vals',
    'Vammo E-Sports': 'Vamm',
    'Vandal Only': 'VAND',
    'Varsity Club': 'NRG',
    'Vela Gaming': 'PRX',
    'Velocity Gaming': 'VLT',
    'Velox': 'VLX',
    'Vendetta': 'VEN',
    'Vengeance': 'VNG',
    'Version1': 'V1',
    'VersionX': 'VX',
    'Vertexo': 'VTX',
    'Vertical Seven Esports': 'VIT',
    'Vexed Gaming': 'Vexed',
    'Victory Formula': 'VF',
    'Vietnamese Curry': 'Viet',
    'Vieux Touristes': 'OG',
    'Vikingekrig Esports': 'Simp',
    'Villainous': 'VIL',
    'Villains Esports': 'VLN',
    'Vincit Gaming': 'Vinc',
    'Vipes Anime Crew': 'SRN',
    'Virtue Gaming': 'VTRG',
    'Vital Force': 'IW',
    'Voltage': 'OPP',
    'Vorax': 'Vora',
    'Vorpal Sword': 'SDM',
    'W Key': 'CES',
    'WALTEM Gaming': 'WALT',
    'WATEr': 'WATE',
    'WAY Esports': 'WAY',
    'WDNO': 'S2V',
    'WHITE TIGER': 'FF',
    'WICKED': 'WICK',
    'WLGaming Esports': 'WLGa',
    'WOLFPACK': 'WP',
    'Waifu Warriors': 'Waif',
    'Walküre': 'WKR',
    'Wanderers Esports': 'SWE',
    'Wanderlust': 'Wand',
    'WanteD': 'DC',
    'Warriors': 'Warr',
    'Warthox Esport': 'Warthox',
    'Washed Players': 'Wash',
    'Washington Muscle': 'Wash',
    'Watch This': 'Watc',
    'Water': 'WT',
    'Waterbottle': 'WB',
    'Wave Academy': 'CEC',
    'Wave Esports': 'WAVE',
    'Waverunners': 'Wave',
    'Way 2 French': 'W2F',
    'We Raise Blame': 'SMB',
    'Weeb Dream Team': 'PASS',
    'Weeboo': 'PASS',
    'Weird Esports': 'F1LS',
    'Western Bulls': 'OBG',
    'What\'s going on': 'DILF',
    'Wheels': 'Whee',
    'White Lotus': 'Ghost',
    'WiLD MultiGaming': 'WiLD',
    'Wichita Wolves': '2D',
    'Wildcard Gaming': 'WC',
    'Windstorm': 'LG',
    'Winfinity': 'WFNT',
    'With the boiz': 'WTB',
    'Wizards Club': 'WIZ',
    'Wolfix Gaming': 'FPX',
    'Wolfpack': 'Wolf',
    'Wolves of Hell': 'AKV',
    'Wombocombo Team': 'BLD',
    'Wooky eSports(Mandala)': 'Mand',
    'World Game Star': 'WGS',
    'Worst Players': 'WP',
    'Wulf Esports': 'Wulf',
    'Wygers': 'WYG',
    'Wygers Argentina': 'Wygers',
    'Wyvern': 'GGam',
    'X10 CRIT': 'X10C',
    'XFlow Esports': 'SMB',
    'XIAO': 'XIAO',
    'XSET': 'XSET',
    'XSET Female': 'XSET',
    'XStealers': 'TB',
    'XTZ Esports': 'XTZ',
    'XcN Gaming': 'XcN',
    'Xiphos Outplay': 'Xiph',
    'Xplicit': 'Rise',
    'Y10.5': '105',
    'YAMAGAN': 'YMG',
    'YAZDA': 'YA',
    'YFP Gaming': 'YFP',
    'YMG': 'GFN',
    'YUMPERIGO': 'Eter',
    'YaLLa Esports': 'YaLLa',
    'Yellow Submarines': 'Yell',
    'Yendez': 'YZ',
    'Yes mies': 'NN',
    'Young and Beautiful': 'FVT',
    'Young&Old': 'TNL',
    'YoungTalents': 'Youn',
    'YourBunnyWrote': 'OPP',
    'Z11': 'Z11',
    'ZAM+4': 'VKS',
    'ZEITGEIST': 'ZEIT',
    'ZEN ONI': 'ZEN',
    'ZENITH': 'AE',
    'ZEROZONE': 'ZØ',
    'ZETA DIVISION': 'ZETA',
    'ZFGaming': 'ZFG',
    'ZHUQUE': 'ZHUQ',
    'ZaPs Clan': 'TheD',
    'Zanga7': 'B4',
    'Zeal Esports': 'ZLS',
    'Zealous': 'Zeal',
    'Zelos': 'Zelo',
    'Zenigma Alpha': 'RNG',
    'Zero MarksMen': 'ZMM',
    'Zero MarksMen Black': 'ZMM.B',
    'Zero MarksMen Silver': 'ZMM.S',
    'Zero Risk': 'ZR',
    'Zero Synergy': 'ZS',
    'Zero Synergy White': 'ZS',
    'Zero Zone': 'ZZ',
    'Zero Zone W': 'Zero',
    'Zeta Gaming': '19',
    'Zeusaberz Esports': 'F1LS',
    'Zillenials': 'Zill',
    'Zoomer Academy': 'LRS',
    'Zootopia': 'NG.B',
    'Zwan Gaming': 'KZN',
    'ZyppanGoKill': 'PSW',
    'aNg DarkHorse': 'aNg',
    'aaaa': 'MF',
    'afterMath Esports': 'afte',
    'ahq e-Sports Club': 'ahq',
    'aim hor$e': 'Rise',
    'alltheRAGE': 'atR',
    'animel': 'anim',
    'anythinglajustput': 'HZ',
    'asdf': 'T1',
    'aspyxia': 'XIA',
    'atreus': 'NIP',
    'avg25iq': '25iq',
    'b Tang': '',
    'bTitans': 'bTit',
    'badcovid': 'badc',
    'beastcoast': 'bc',
    'big pizza': 'BigP',
    'bonk': 'bonk',
    'breadHUNTERS': 'brea',
    'bref': 'bref',
    'breskvice': 'MB',
    'calclub-p': 'calc',
    'chess on crack': 'VIT',
    'cismix': 'Tact',
    'ciszej': 'hu1',
    'clowns': 'GV',
    'clownz': '0.5',
    'come next': 'come',
    'corgi': 'corg',
    'cowana Gaming': 'CG',
    'cute fat boys': 'C9',
    'cuties with cooties': 'cuti',
    'dATHITANS ': 'dATH',
    'deathwish': 'deat',
    'defkon': 'defk',
    'devils.one': 'devi',
    'done(doneVAL)': 'WYG',
    'dont test our gangster': 'nmDM',
    'dotExE': 'C9W',
    'down bad': 'db',
    'driveBy': 'ARDE',
    'eMonkeyz Club': 'EMZ',
    'eRa Eternity': 'eRa',
    'eStar Gaming': 'eStar',
    'eSuba': 'ES',
    'eUnited': 'eU',
    'eXiLe Academy': 'DRM',
    'eXiLe eSports': 'eXiLe',
    'earnings: 0': 'ZEIT',
    'ehehxd': 'xd',
    'el bdoon': '',
    'epic gaming': 'TB',
    'esoteric': '5gg',
    'euphoria': 'euph',
    'ever.wc': 'F4Q',
    'ex-AING MAUNG Esports': 'ex-A',
    'ex-FLICKBAITERS': 'ex-FB',
    'ex-FULL SENSE': 'ex-F',
    'ex-Five Ace e-Sports': 'ex-F',
    'ex-Giants Gaming': 'ex-G',
    'ex-Limit': 'ex-L',
    'ex-Morph Team': 'ex-M',
    'ex-O2 Gaming': 'ex-O',
    'ex-Ravens Esports Club': 'ex-R',
    'ex-Reckless Lads': 'ex-R',
    'ex-Recon 5': 'ex-R5',
    'ex-Reveur/Team Phenix': 'XcN',
    'ex-SV Empire': 'ex-S',
    'ex-Serenity': 'ex-S',
    'ex-Serenity Black': 'ex-S',
    'ex-Team Bliss': 'ex-T',
    'ex-Thailand Attitude': 'ex-T',
    'ex-Timing Monster Gaming': 'EXT',
    'exuLt.gg': 'BF',
    'ez5': 'ez5',
    'fReya': 'fR',
    'fastmix': '[A]',
    'favela aimers': 'fave',
    'feelmyhack': 'THEX',
    'fiVe': 'OOW',
    'fish123': '123',
    'flawless': 'flaw',
    'forZe': 'forZ',
    'fostercare': 'FC',
    'fully': 'Exor',
    'gucciGANG': 'gucc',
    'h$666': 'Fea',
    'hREDS': 'hRED',
    'iCEGunmandu': 'iCEG',
    'iNSIGNED': 'TQ',
    'iPon Esport': 'iPon',
    'iXA': 'DGW',
    'ifyouhappy': 'TEN',
    'illusioń!': 'Illsn',
    'instalocked': 'IL',
    'iwnl': 'iwnl',
    'jaba': 'Mang',
    'keepYOURskill': 'ky5',
    'komand04ka': 'kom4ka',
    'leões da Ranked': 'TREM',
    'looking4org': 'L4O',
    'lvlUP': 'lvlU',
    'mSpaz': 'mSpa',
    'mens))': 'mens',
    'mhm': 'T1',
    'mix(Mix)': 'Mix',
    'mixenergy': 'SAW',
    'mouseSpaz': 'mous',
    'nA Whiff Masters': '',
    'need more DM': 'nmDM',
    'nevermindgg': 'nvm',
    'no name': '',
    'no org': '',
    'noFEAR': 'GUILD',
    'nolpenki': '0.5',
    'notbuiltdif': 'GIA',
    'novidades em breve': 'GLB',
    'oFby': 'NU',
    'onemoretime': 'onem',
    'oogabooga': 'SQ',
    'ownage': 'owna',
    'paiN Gaming': 'paiN',
    'paroXysme': 'TYE',
    'peanutz': 'pNutz',
    'pepecool': 'FaZe',
    'pick me up': 'FaZe',
    'playzone': 'pz',
    'pokas ideia': '',
    'project_kr': 'PK',
    'putsch': 'K1CK',
    'qz': 'PLS',
    'raeB\'s Anime Club': 'The',
    'random5': 'OXG',
    're\'born': 're\'b',
    'rice and meatballs': '100T',
    'roLLed': 'CN',
    'roughtimes': 'RT',
    'sameROFLMAO': 'same',
    'sas elle': 'sauce',
    'seeker': 'seek',
    'seleção': '',
    'shiba n the homies': 'SHB',
    'slime slats': 'FaZe',
    'smoke': 'smok',
    'spongebob squarepants': 'spon',
    'steven edge le': 'boom',
    'street\'s sentence': 'flaw',
    'swag and friends': 'swag',
    'swieca mix': 'BST',
    'tAfz': 'OOW',
    'tba': 'tba',
    'team cotch': 'team',
    'team flavor': 'TSW',
    'team xz': 'XZ',
    'that cool team': 'LAUNCH',
    'the boomzers': 'boom',
    'the gu krew': 'tgk',
    'thunderPEEK': 'YZ',
    'tiobarão': 'tiob',
    'together we are terrific': 'Terrific',
    'top500 and dog': 'top5',
    'trying to win': 'M5',
    'tryouts': 'VLT',
    'tyeasy': 'TYE',
    'unKnown': 'Blit',
    'unjobbed': 'unjo',
    'unnamed': 'unna',
    'unsigned': 'unsi',
    'v0rteX 5': 'Hamt',
    'vanished': 'vani',
    'volei e peteca': 'hPw',
    'volvo peek': 'VPK',
    'wafflemakers': 'RAAD',
    'wasd fan club': 'wasd',
    'waterdogs(thunderPEEK)': 'SS',
    'we dem boyz': 'ez5',
    'wesh guys': '',
    'wicket berg': 'WB',
    'xCeed': 'RevX',
    'zTitans': 'GMT',
    'zazemlenie': 'zaze',
    'zesty\'s money crew': 'GEN',
    'zytic esports': 'OG',
    'ÉPEGADINHA': 'BAR1',
    'Øutsiders': 'MRS',
    'İstanbul Wildcats': 'IW',
    'świeca': 'świ',
    '레.스.고': 'VVS',
    '이사가자': '이사가자',
}
